name: Zest CLI Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  os-test:
    name: Run CLI tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Build CLI binary
      run: go build -o zest main.go

    - name: Run tests
      run: go test ./test/... -v
