name: Zest Release

on:
  push:
    tags:
      - 'v*.*.*'  # Match semver tags like v1.0.0

jobs:
  build:
    name: Build and Release Binaries
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Set env vars
      run: |
        echo "GOOS=${{ matrix.goos }}" >> $GITHUB_ENV
        echo "GOARCH=${{ matrix.goarch }}" >> $GITHUB_ENV

    - name: Build binary
      run: |
        mkdir -p dist
        EXT=""
        if [ "${GOOS}" = "windows" ]; then EXT=".exe"; fi
        go build -o dist/zest-${GOOS}-${GOARCH}${EXT} main.go

    - name: Upload release binaries
      uses: softprops/action-gh-release@v2
      with:
        files: dist/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
