name: Zest Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write   

jobs:
  build:
    name: Build and Release Binaries
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Build binary
      run: |
        mkdir -p dist
        EXT=""
        if [ "${{ matrix.goos }}" = "windows" ]; then EXT=".exe"; fi
        GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} \
          go build -o dist/zest-${{ matrix.goos }}-${{ matrix.goarch }}${EXT} main.go

    - name: Upload release binaries
      uses: softprops/action-gh-release@v2
      with:
        files: dist/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
